### ISSUE TITLE
Mass and gravity

### ISSUE THREAD

**Issue by fabienbaradel** [ogroth/shapestacks#2]
Hi @ogroth and thanks for releasing your code. It works well! Is it possible to determine the mass of an object (cuboid, rectangle, ...) when I create a new scenario? And the gravity of the world?
Thanks

**Comment by ogroth** [comment]
Hi Fabien,
Thank you for your feedback! :)
In the scenarios we have released, all objects have equal density (the MuJoCo default of 1,000 kg/m^3), so the mass of an object is directly proportional to its volume which is specified in via the geom size attribute (see the geoms in one of the [example worlds](https://github.com/ogroth/shapestacks/blob/master/data/shapestacks_example/mjcf/world_ccs-easy-h%3D5-vcom%3D0-vpsf%3D0-v%3D1.xml#L20) for a reference, the MuJoCo default unit is meter).
If you like to see the masses of the generated objects, you can add a line to the generation script when objects are added to the world to print out their volumes, masses etc. The line could be added around [here](https://github.com/ogroth/shapestacks/blob/master/shapestacks_creator/create_scenario.py#L509).
The gravity and many other high level properties of the simulation are set vial the options in the top-level env_*.xml files. Our gravity is the default of -9.81 m/s^2 in along the z-axis. For a comprehensive overview of the MuJoCo flags, please see their excellent [online documentation](http://www.mujoco.org/book/modeling.html#option).
Oliver

**Comment by fabienbaradel** [comment]
Thanks @ogroth  a lot for your complete and comprehensive answer 👍 I appreciate
