### ISSUE TITLE
Only first frame image is provided?

### ISSUE THREAD

**Issue by Wuziyi616** [ogroth/shapestacks#27]
Hi, thanks for open source such a great dataset. I have downloaded the RGB images and unzip it, but for one data point, I only find frame0 images `xxx-mono-0.png` with different camera views. Does that mean the whole falling videos are provided? Would be possible to upload them for download? I understand the dataset should be very large and it's been 4 years since the dataset release, so completely fine if not possible

**Comment by ogroth** [comment]
Hey Wuziyi616, it's correct that the dataset only contains the first frame of each sequence which was - back then - a trade-off between usability and dataset size. However, all frames can be regenerated using the [recording scripts](https://github.com/ogroth/shapestacks/tree/master/shapestacks_renderer). MuJoCo is needed to run the simulation. A quick installation guide for the repo is provided [here](https://github.com/ogroth/shapestacks/blob/master/mujoco_installation.md). The license is free by now and the complete simulator has been [open-sourced](https://github.com/deepmind/mujoco) as well. Hope that helps!

**Comment by Wuziyi616** [comment]
Hi, yes, I'm looking into the data generation code now. Thanks for the reply!
